### PR TITLE
Add generics for contract type-safety

### PR DESCRIPTION
**Pull request by PHCitizen**
this is the implementation of the snippets I post on telegram. Types are a bit different because I make a fallback if "any" is passed. this is needed if the user are using javascript or artifact are imported somewhere, and we cant infer the types

[latest ts playground](https://www.typescriptlang.org/play/?target=9&ts=5.4.5#code/PTAEBcFMGd1BLAtgBwDaUZAduAhueAeywCgBjVXaaUABQFcAjAa0gE8BvE0UXAEz4AnGNAAUASgBcoWIPhYA5qC48ew8PUFZQAIh3dQAXxLGKVGgGV4ClaGxlCfSBOmz5S22sgatu-T2NjEhBQAF5wiMio6JjYuKjgsABZXAV4MkSw+Oyc3IiScDZkSDp1AgAzNgAeABUAPjDlUABtAGkEbVY2QnLQGoBdaRq2-qNQADJlQwBuAqKSgGFiMnwa+jQYWrsADygsPhpcLDZm-oAaUABVHb2D3mPThtCWgDo3mou3l8vRkjnivrzFLIRq2HSMQiEVA6aQQqGQI5nAw6eTgGGgRjWVFIng6NyKdH4hQ43SMNhQaDoy6ogAcAEFBIJcGwSeDyTAACxU2kMpks5FkikAZgATNycPTGczWYKYAA2LnSakS3nSgXs6AARnF4ElfNZyCYXXRDBY7FZ0Gs6KsxORfHwVCt0htSOMhQBNSBuGQADVcKh6CVnp7isDml0eoDQ97+n8QgAxQiCUBMgDuMnAckU-xKAEksOVIIJaLgmYhoLUnn0btg7gADAAkHHkheTIcghlATZbRdAADlcJhDHXQAYeAB+KMlSC7Ws0CO9dvA0eqVSTgeYGv7GiNjhEwwXbsF3sAeWHK9Xl8nSywK3Aaw2FeaS+9z-m-XOoHzrZLZYrJ7qOox0vHhpDfaNkHAyAP2A0DQCwSAADci2A6QEOQwRZhzUAAH1vyLeMsErRoai3esm33cp6FvAhiC7Ztj2TPtDFEI9WzoQxxDY09hwMSdRFgugyJoPQLxAycOHDDp+0GUAJDCBojjYMZBLgyTmGkvtZNEL5kGkfDi1LQcK1oOpxAU+5lOMVdzMmPDGMIqoAIMaQODdeYvwcoj6kaWgyngSoqns1tHPqIDMkTZMHBQeB0D4XhMWwgBxbx2zpaAH3QYjngMUiZ1uGhhH4YhUGU5oe2TOlPjeCrQBPWNV0nOlhKad1IGkWr2yMQTJy6-K51ABcp2XVTQEnKCw3bT8vhS+95nSzLICcupfhAuDmiU6qXlmtKMvWLKAIay8wM20AZtS+a9o2ZajrgvLZ23FpVqvJ7BOkJTTj+NrcIMpYYri0Kq1ylqOFAdBFHAAALDrGNAAAZbrGvhlqsHoRBGF7Hrq36x6ir4Eqytqqqzpq2H6rEl7mpxu5QawQd2ozLNiQ6Q1wGgaQ8YJyzTkRtaJ2UKT5FAOlmh0OnMB0D9pB0t49NAHbLsWqoRZRLBWcpfozIspSxjs37CH+yA+Ec5y+bUzs9cYv7kFio2TaAvmhhaz6zbGqZVNclpmFcTN3G03T3oefpzNCRTjl51dPfDH2mf92XA5OYPtfD6zVDQpCUO+-XDeN7yqz87wKmqYKi2t23c8rcLMjyGva4SBMk1ABYqEh6AyDkZA4BvTNcDIcBq7rwe8j+MxqCb4ge77qoDAcLBYCuEHZ9keg+6TfN1Y5hF8awUruc-XBMU34qd+Uj7+lTnhng4JfMxX8A17V+g2YT04LgP+AX-Pi5gepmhQZvwQd8H4b2Gt6P0AZICv1AFRGiRA57SAAEqQAcIIPgVQiRv2OA0C+oJQAAKAYIdeT92bywusUBa+0lqXFFvg1ehDH5s0lnUC4MC+5wJIdnG2AMiLUJ0O-JhvMGi2FYbROeABCIYosRHsMln8HgtD76CFEKWCovdwBKguMgIy5ZJE6AUcA4hktzJuRMH8AeQ8LFxEyDUAAohYGoFhzGWOcZEEexB54qICmozUoIZ7uNvnQohz8WgcHFgzPhjAyA6AuG1aQeIrSGHOAYd+khmjAU8KoMJcTGD0DYNEwS8gQHNFCfTOJlIYnzDKVaIwt1eaxk7FQPB-i4xgEQvAXATS55wE8eUNRoAtFlnIP4zpk9wAckaAhdM3cmR92UYIVRfdNQXGaJM0ANoJDByGTgGZYyXjSPcS8HJbBRCrPWeIcQLTeDzK8X3Xghxw7PCwIQCA8wAC00BcCFkKFs+es9RkAFYJmQCmRPHZcyFngB8Y006zRNQAAYEVYAuHw44UN3BGK2QCvZ1E2EHKoHwZgAArRg+LCXMBOcCtZ1gJAXMyIgI49B-TYQACIwHgMIPg0y+lXz8V0wBgSGEkOaC6OgRp2BJJ4Ps+ByhgLQEgKgVA0tkCCEhOUJUPIpRsBDmHNgBhAg-LgH8nZcogUgu2Woqop1WWWg5VyvudRwU3MhXcyyyzTnUvEBcVZpougbIuUatRcpsWwIOXKhVFL0zKl1KqY55yzEhAAOolBWDgDo7F4DgBYf6VAJKyAaXvpZA1VyIUil8fI-x-LFFBKFSUzAcSD5RIqcUKpCgdCJJJCktJq4Mk8CyaSXJ+SQKFOIWBWt4TykvObboS0raanAVTvUotAa+4AHZTXj3NbMnpaiRTLM2cu8AK7g24rni8MNqAI1XA1XyGllyXH3syCeOGzKnH3qHm4rpIydmagsIQTQZAgygDrAe0ASRkHYCoKIWU0ARRwpTMg+ANtsCZoxBqWD0DqJOEEBcVE-S4oKEgMAAAVDh1NxQ5COFAER4AxjgJSvgwB+AyF5I9tUCEYQABHeg7LnDgG2C8VIJQ6jPHI0QPg4gsJ8xCAsSGyD82Q3wBAWT0D2Xzz-eAVmMgBoFqhiUYQZBEPwGQ6NTj3HhCiD4y8dT6tmhwv6C8VAhA83uAAELsgcE4LI8FKVwyc8wVz7nHCQFoCKWgrQAASoh9OGeQ+cyTa1cOIHkARSAgH4UItmHzXDZBNDCBwOAwMjRLPDrZs0NF0ABNsOQkE-MThtj2cQv6QMmWEuprIApxQkACuAZy4yZD3XQCvLw0bAjg3QBJYQoIeMqX4sgRCLmXounhAIBoE8uA2A-0KEhmDSA5Q4DlEbkRo4hAltEeG3wUbnyoDJnK6AYgkALiphKHK-YSm9MYFwPILDEBnm6YYzFnAo0QgniW6meAcrQBPa069v7wh6Vfd7Dp5T0WkOpqOPFP77Wjijdzfm37ymD2jQCnJLHnWBtVBE-hkoABqcbyWpupdo67LwXGeMWf49Z4htmGtNaDM8XreXwADaGxNlLkAJOjU7PKiHrGQKmbZ5ZznpW7MvEaxArzGwLvi5a67eX5nFdPxs5qezjnnOKDc1ADzfOID8ZK9AMrkNweVYINVhhtWZwm78wFy3QWJfM-g6z-XHPDdc+N6r3nXnScEe637taOCgirno-pygSBRCGjNMpZAzALgzpkEztaevnAKegJDTUco4Vp+YCHZ4MCsOx7l5AQPzh2tyfWdATRVf6-dV4jfL93j9JeSqG1SMB6f1-sEABqsbkXU60xd+l4+nIBMecP60F3iF-IJT4gS9Pr2ASC9ZSs5FyQgAAE2avJnMUPuF-GSN1u4geg88iwquTBjFYj+ShQ80zaDosAt53d6F311VHw3zMFT3dQUH3283TCPzMWwgPRFF-X-UgGeDrHoxez4DTzFUzyr1Gn90TxxVETwS3ywIz36WzxkGsBkAuDhFQAgBgHAFoJz19kUHoNgCSGgAUHEDrCXTXz7hFAHxCiIgQKQIn0gCnwaXuWUjnx3TPVrB32wNvQQJeDAO329UUM9WgKpUgM0Nvge10HxR0GPzADP2gAv22Cv3ABvxfyU3B3G0f3W1v1f2QVwA-0hxKG-yoPkD-34AANFQzxkP4JUJIIgKgNCLjTgN7wPSFFEIAzLQSg-i7VUFYz7XBAHRJFXDtzAlGjHTKWiUnXHWqQPByNSKz3yNiWnRYNnWKJAlqRqOSMElSPPUHUvCyJaBKNKV0DKKbXCXT2NCMAyNUDqIMHqRdRvl4M3XACFEENLgNi4TtiImH16GiNiMgQiXgAESvkkMLWiMOVyUvTOWRSMMCKmLkPDXUIz1vVP3P0v2QSsOfzv0dxoAfyfycIxBcLcK-yfm0N-ygF8MjCJBOKFD2OOXCJiUAXFyAA)

btw i remove infer using string. i think if they will use it, much better to use interface and define type there.

### CODE REVIEW

**Comment by rkalis** [comment]
Hey, this is really cool! Thanks for creating this PR. This functionality would be really nice to have, we saw that there's some TODOs / refactors still needed. If we want to integrate this, then the inferring would also need to work for the `unlock` parts of the contract for sure.

We will have more bandwidth to get this implemented / integrated once the debugging tooling upgrade (v0.10) is released, so we'll get back to this issue after that.

**Comment by PHCitizen** [comment]
on commit [90191fb](https://github.com/CashScript/cashscript/pull/192/commits/90191fbc8df943bf5c59b9e7c3312c2d34bdbb0b) i use ignore that error, because we know that it must be indexed and we are setting the right value
if we don't use ignore, we need to cast type manually

```typescript
const name = f.name as keyof TFunctions;
this.functions[name] = this.createFunction(f) as TFunctions[keyof TFunctions];
```

**Comment by rkalis** [comment]
Hey @PHCitizen, just want to write to let you know we haven't forgotten about this PR. We've finally released the debugging functionality with version 0.10.0 earlier this month. We will finally be able to pick this PR up in November. Thanks once again for the effort thusfar, and we'll work to get this integrated in November. 🙌

**Comment by mr-zwets** [comment]
Regarding completing the `TypeMap` as documented in

`// TODO: use proper value for types below`

a back and forth with chatGPT suggested the following to include `byte` and `bytesX` types

```ts
type GenerateBytes<N extends number, Result extends unknown[] = []> = 
  Result['length'] extends N
    ? never
    : `bytes${Result['length'] | 1}` | GenerateBytes<N, [...Result, unknown]>;

// TypeMap with dynamic fixed-length byte types
type TypeMap = {
  bool: boolean;
  int: bigint;
  string: string;
  byte: Uint8Array;
  bytes: Uint8Array;
  [K in GenerateBytes<100>]: Uint8Array;  // Generates `bytes1` to `bytes100`
  pubkey: Uint8Array;
  sig: Uint8Array;
  datasig: Uint8Array;
};
```

**Comment by mr-zwets** [comment]
ChatGPT also suggested a possible solution to the nesting in `GetTypeAsTuple` and suggested renaming for clarity

```ts
/**
 * Converts an array of artifact parameters into a tuple type representing each parameter's type.
 *
 * Example:
 * If T = [{ type: 'int' }, { type: 'bool' }], GetParameterTuple<T> resolves to [bigint, boolean].
 */
type GetParameterTuple<T> = 
  T extends readonly [{ type: infer ParamType }, ...infer Rest] 
    ? [ParamType extends keyof TypeMap ? TypeMap[ParamType] : any, ...GetParameterTuple<Rest>]
    : [];


```

**Comment by mr-zwets** [comment]
while further trying to improve the types ChatGPT suggested sometthing similar for `InferContractFunction<T>` which solves the deep nesting and combines the `Prettify<T>` and `_InferContractFunction<T>` helper types

It needs careful review and testing! but solving the nesting looks promising for maintainability... 👀 

```ts
/**
 * Infers function argument types from an artifact ABI, producing a map of function names to argument tuples.
 *
 * Example:
 * If T = [{ name: 'func', inputs: [{ type: 'int' }] }, { name: 'otherFunc', inputs: [{ type: 'bool' }] }],
 * then InferContractFunction<T> resolves to { func: [bigint], otherFunc: [boolean] }
 */
type InferContractFunction<T> = 
  T extends readonly [{ name: infer Name, inputs: infer Inputs }, ...infer Rest]
    ? { [K in Name & string]: GetParameterTuple<Inputs> } & InferContractFunction<Rest>
    : {};
```

**Comment by PHCitizen** [comment]
> ```ts
> type GenerateBytes<N extends number, Result extends unknown[] = []> = 
>   Result['length'] extends N
>     ? never
>     : `bytes${Result['length'] | 1}` | GenerateBytes<N, [...Result, unknown]>;
> 
> // TypeMap with dynamic fixed-length byte types
> type TypeMap = {
>   bool: boolean;
>   int: bigint;
>   string: string;
>   byte: Uint8Array;
>   bytes: Uint8Array;
>   [K in GenerateBytes<100>]: Uint8Array;  // Generates `bytes1` to `bytes100`
>   pubkey: Uint8Array;
>   sig: Uint8Array;
>   datasig: Uint8Array;
> };
> ```

does this one compile? i cant compile it. anyway i expected there that the number are fixed and did not allow arbitrary number

if any number can be use i think we can use this one
```ts
type TypeMap = {
  [k: `bytes${number}`]: Uint8Array;
} & {
  "bool": boolean;
  "int": bigint;
  .....
}
```

**Comment by PHCitizen** [comment]
Regarding to other improvement listed, i think i encounter that before and that is my first solution/attempt.

Then i came to place where "any" messed all up, so i try to push it futher and ended it that code😆

But maybe im wrong? who will feed "any" on that function. Anyway i think most of the user that will ended in "any" are those who uses JS, maybe they do not need type support or im thinking if the edge case error will show/not on them

**Comment by mr-zwets** [comment]
> does this one compile? i cant compile it. anyway i expected there that the number are fixed and did not allow arbitrary number
>
> if any number can be use i think we can use this one
> 
> ```ts
> type TypeMap = {
>   [k: `bytes${number}`]: Uint8Array;
> } & {
>   "bool": boolean;
>   "int": bigint;
>   .....
> }
> ```

You are correct, my attempt did not 😅 thanks for the correct way!

> Regarding to other improvement listed, i think i encounter that before and that is my first solution/attempt.
>
>Then i came to place where "any" messed all up, so i try to push it futher and ended it that code😆
>
>But maybe im wrong? who will feed "any" on that function. Anyway i think most of the user that will ended in "any" are those who uses JS, maybe they do not need type support or im thinking if the edge case error will show/not on them
>
>will look futher soon

@PHCitizen it would be super helpful to also have that code if you have the typescript playground link!
I think indeed `any` handling might not be worth the additional complexity 🤔

**Comment by PHCitizen** [comment]
> I did another attempt to simplify the typings to increase maintainability & simplicity of the typescript code. I named the generics to make it more clear what is going on. Here is the main part:
> 
> ```ts
> class Contract<
>   Artifact extends { constructorInputs: readonly any[]; abi: readonly any[] } = {
>     constructorInputs: any[];
>     abi: any[];
>   },
>   ResolvedTypes extends {
>     constructorInputs: any[];
>     functions: Record<string, any>;
>   } = {
>     constructorInputs: ParamsToTuple<Artifact["constructorInputs"]>;
>     functions: AbiToFunctionMap<Artifact["abi"]>;
>   }
> > {
>   functions!: ResolvedTypes["functions"];
> 
>   constructor(artifact: Artifact, params: ResolvedTypes["constructorInputs"]) {}
> }
> ```
> 
> 48 lines compared to the original nested 78 but it also removes the `InferFn` & `InferCompiledFn` helpers which might be helpful for manual typings
> 
> [typscript playground link](https://www.typescriptlang.org/play/?target=9&ts=5.4.5#code/PTAEBcFMGd1BLAtgBwDaUZAduAhueAeywCgBjVXaaUABQFcAjAa0gE8BvE0UXAEz4AnGNAAUASgBcoWIPhYA5qC48ew8PUFZQAIh3dQAXxLGKVGgGV4ClaGxlCfSBOmz5S22sgatu-T2NjEhBQAF5wiMio6JjYuKjgsABZXAV4MkSw+Oyc3IiSEnA2ZEhQABViyBTkMOUDAG1maQADRjYoaAASDix6REZIQUNmgF1pAFV5cAAOAEFBQVw2AG5QEJTwMgALGF4sNl02joAeXv7BgD4dUGR8KC0TUAAyOp4dI8gdCam5haXlgzvdowL6gSY4X6LFaAxiEQioUGw+GQXBYAFvKaI6xTdG6NyKUH4hS4nTIJisNighgsdgk6DWUFWYmAvj4KgM6RMgGGAGZADCxAAboM4KjeH8DoQAGY3XCLTD3UBOKXyeAEYg0KaEXgQehoSCZACiAA9cCh0NJ6hwIJVpKTyexroYADTKG0lO2YowjUAAWguoHq4Jm8yhrsY2JwI0KlTocrN0DKhDKevQx1o8cQ0ADoTj8pokGNUCwfBown4xFQB3q8ilg1AAAkUXxXQA6du1+tlXDwVDRngAfkbzbsRewpbdRQ9CCwdcE5VjxlUoCH9QqJWqa9jLwp0oXG9wyBGbfbGfzSZT+uO3d7F37qktqLYJ9bZ4TF9TkGvPdQd4MlpGXkQgASVnespXoLAyHVLAaClQRCEQUBZgAIWApVIBVLA1SIWCjVNc1IEta0sDNIjdHARZYLnHRXXkMlwGgS121bH1DB9f1Jyo6A52kUQWLlBQmMDFiRnEMIAyfIwYxKZCIyTAAxSDoNw6pjlmCMczk+BR2LCdyz4Stq07ecm34F8TPKH97yHMy+F08caBIsjpEsgA5MjVno+hGNcsD51AhiaCXVQh2teoAGkZ1ADzMGeGRKPcMZQH49tBOEt8sw-K9Ap87NxNCST9iMeKNPgRTlJgtSb1-AweGkMqKqgqrD2-W9-2UHkChCPJer6hIQgFHBFmg0A+UoahMn66beoKMxqDG4hKNwaDjgMeYCClFa4ELPSnNABxYMo+hoMIQRct80ADKMvY2HqQDeAjaRrqwKtbvukrc08A6NWO07zqwILpCfe7cR4XAnvewCDBdAwACUYHhYV7N2xzXlUQ7ZBO8Azou4SQeh5cIOa3DhIRhxBD4Y4iVdJ8LlxQxam+zG-pxgGgbzd9k0-dTBE27b6h0FnBGx3HAbynQRnpurQGJlSNQa+TCCUkniDUjb4C26DBYh+BJelgISADWw5Zg6AAEJpAR6AkcgPhBdN0nJd5HhhdFwRRDlfnoIavnNe211bnzK3EdQZHBbd-68cl8SOECAoppmpP4kyMpDQsMoLET5Oc4SchfvFb3wAARiZgxI7ZvHiNIzA7QhshaPdcidHpBQdHY50DF1yR6hl76eBr5vGHoSlO+XHhvMuq1B7taBG6nZvW6de9DZ4aNGaoH6ju6sBBXgXAt9gQv-dGoOzXzo6t+W6CABZaiwSAAHdFuG7bPb9rWS9deoH+fpkJDEhfa+4Ab6tkdhqVsw82CiF-qAf+4hxA72Pp-XgNApK5iwNqBevpoC4DrEUC+R9DrAIAKz3yfi-YB78i6l03k+b+xcAAMzCsCuh0E+cAWx3AxyASNcAJCwGVVJq2KgfBmAACtGCiPEcwGBFD4GIMyIgVE9BcCoBkqUAAIjAeAwg+BDWAWXV2v0RZR3FlPJkrpqQUmPAYcBsFpDfWgJAVAqA+LIAQtKb4EJQxLAKkVNgMMTCELgMQvhAA2chz8DF8OOPQ0A2j6R6JidtC41CT4l1Qbdb+sD4GulgdY9gADEFhO2uEwRqtYKtmca4uRz9gyQiWBIRRmQADqpQyCojgJZNUrotquKkWQZgEBtRPhCcg7aAAmIxh9WZiw5tPFyuh67z1tHiBkHcu5PV7sufuoAZ6HBHrRGWE9zHCUWbXPEqzpwtwZN6GWIV17jNKdBAA7FEyhfD0mf0md-QBLzwCvIqfLKpNTUB1LBD8Xx0CEFINzvCzIAB5AAMpo7O8Kk5zQLgC4uFhCCaDIKUXMzQAWgCSJAQlpExAfGgJMxhV0KXwGQPAbA4BwzAlpfS4mThBB0RwDcdAfAFCQGAAAKj5XAEochHCgFFcAWOMt7EMsJfAYUEh0bjzWGAYQABHegujnDgGNCI4VoALi5ilUQPg4gXaaq1WNHYQyIBbHwM60oKpBBH3xeABiMg0Y4zdcqplLKcAnNULq-VwhRBGtbN6oK9RGEjFbKgQgQz3AoWBA4JwWR9kUORam5g6bM2OEgLQSZtAIoNlEMIMgwbWUINtZqqYoBEDyEGApSARLQBMOYWDcezayCaGEDgAAamo+gXaY2T2gPUTh8BoAiJUsKC6oEnDGiTYKcdkA+3LgHS6xQkAx2oAnbUQdCxWVHpPb6AVdtTXXtbQ-QQHbt0FDtfa4CMpOGDFKPO-ZhAdqYPoAoLYoB0BSjgFKM6srUT-p2IIUVN6hWlDwYqOdNBiCQFdI-UoziSyBuEMo+QPKRn4cZcy1lYaeAhERV+wQj952lGw36vDX6GWEZLPWANrGa11v5aieyrHtiolNYM4ZXGdhXz4ZRhAMpRBCYPZe0oxwLWCtNQAahbW2p9naFVvuXBGg10bjVxrygmjdW6c1nuHeARTfpNOPufTa6TjMXHOI1XpgzUaY0mcYmZ1sm7j1EpU7eyATm9PhsgHqwz3mfLxuLkmlNabFAZqgFmoLEBjXTtnVwhd21VWQBXRx9dyaC1FtSyWsL4WGVRa88Z2Lpn4v+Ys+EA6+7hWKcq5qkKhtFVCOIMqygSBRBkhpAcZAzBXStxkLpu1nnnAuugFsYu4TGHDeYAVXM3LBidfHnNuTjrmD-2gIHdbO3AjNGeUtPhxdpCgTnApLAxwF57hxXiglkAtJxyyVJXh21i6thrZAfLEhfvQX+zWwbiAIWFJhfk+R1hmmZAAAKMV9IWEo0E0cLCg2hlt9Aj6DAQvOAYnT8eMdKL6pkM5YAjj3DD0HJcAcUshxCvJua-4I9hQnBekmplvcEIS4lSrcN8GGw6Mb63pNVfHkqswQ2RsUhuBNmQ1gZDhjhKgCAMBwBIlQJNxKigtewCSNABQ4gLss159BSZt3-IPeOACyZ-PCWfY3mg4qDPJnVPHND8XiPHetjl1DgpfvxBw45woCQrpjqYeWdAPgOhEEhBR9ANHxoMfgCx0T51v7ED452tj4nFLcBk9AExynqv5A0-4KAOn4vPeB5Z7kzn4e4Gc5aViy+AKADMzuu22G7js1QeyDnvCOWPftZzLTSZ6Eslu1zF53Nhm+2flzSTMAX7PA3bcjAT+XCvXffcw2j7BccptU-Awz9H+NzfugFeOkP5qg-jzHibxZpd1+0Fu+27nAKFAvY7Z7dnsZQe8+8dYIx9YmY3dboGdu9IER5WcW8-ASkrtto4CwVfdRtEdk9Ud0cKVM9Cccccs8cCdC9QAScS83Ny8fI28lAq8oAa89wiRYD4DoFm9I8w8IARZQsgA)

On ParamsToTuple, if we pass type that dont match on the typemap, it defaults to UintArray

Solution: add extends to infer instead of using `TypeMap[Type & keyof TypeMap]`
```ts
type ParamsToTuple<Params> = Params extends readonly [infer Head, ...infer Tail]
  ? Head extends { type: infer Type extends keyof TypeMap}
      ? [TypeMap[Type], ...ParamsToTuple<Tail>]
    : [any, ...ParamsToTuple<Tail>]
  : [];
  ```
  
  
  and also adding `ReturnType`  generic args to AbiToFunctionMap, instead of infering the return type as any. But im not really sure about this one
  
i think the best way is not to return function type when using AbiToFunctionMap, instead just return the result of `ParamsToTuple`

To make it simple, what i really intend is to simplify return type typing specifically for `Contract.functions` and `Contract.unlock`

**Comment by mr-zwets** [comment]
I found the original on telegram! 😄 👍  https://t.me/bch_compilers/7456

>hello just want to share type-safe "infer" for cashscript contract
but currently its for contract functions only (not for contract constructor)
>
>but this need to change how the js function are called, thats why im not sure if you will like it😅
>
>i mean of this
>```contract.functions.some_method(param1, param2)```
>
>it will become
>```contract.functions.some_method({ param1: value, param2: value})```
>
>but the advantage are autocomplete on available functions method, and error for params, (eg if we have class for every >paramType, ts-server can error if invalid class are passed)
>
> [TypeScript playground](https://www.typescriptlang.org/play/?ts=5.4.5#code/C4TwDgpgBACgThYwCWAzEAeAKgPigXigG8AoKKAbQGkpkA7KAawhAHtUosBdALk+q4BuEgF8oAMmIjhJUJE7gIAWQCGYSHGx5CWKBAAewCHQAmAZygAiMAFcARsxCWoAflj3HUMlD66DR0wtLM2QAc2c3AGUw719ZRSgASTpUCDgYFTgVAFszLQJOPUNjcygAAwASInpUuAVIMSqatKgAORyIETKvcnI3duzofxKLSuqUloBBEQAaKCaJuoB5Lp7e9bciSkZaBkneeuU1DWxFPDFJZNqMrNyMJbxvdfI+LYod+jaOg8PVdTTTpBzk8fFA6BAAG5pYRyaBXNIAMTo+R0RQCpTGZmAcHooREqBsdAAxihWAwFrU2iIABQUlowEQASjpyy63jc1JB5BgaJGVmcXN6m3euzaByIYjEgpexBFn1aB3giBQ6Aw8PSmRyeRgOGB60ZEiSiyR9xwsSkJEtsKNtQAwmTsSoSdheYEoFicXRQtpYAgkGhMOqTbg8MM3c06gBVNbCmifRzsKCRg7UsCa3J8SMCA34PAqOggETm8FQuCWkgAegrBHwtbr9YbjabzZb9cr1awAFFIlhIu2a63B0Ph7XLUSyVioOO6I6SZFWDY4EToIQytPZ8AoEoIMu6CozNS7CAjGYAEwABigCCJyDAyGMwDmR5PF6gBNMaTm9E3YAANhATFCCAKwAKi-GcoA0ZBWBMKAQIrA1SHWd8SWghhrwgZAoWpRDpSgKsrwgABHGxkAQalgH0AA6FQgKgHBCCgmDGRkZ5egI20AAsdx2YBOJUTc+OgVAyMnBdgFsTczD5YBWCgITCJvO8HzwhASLIiAKOo8TJLMChzy4Kjf1YIlGFxAAhY8dxgldCHBAB3KAABkTLMr1LKMccTAgGBTxgKgAAlqWvW97xnRkWMtNjyG-KBsnoREIBXKAAEZz3S4Rot2TciUXBAZwANRUX8bGSyiqPoXSKD45AzBo1CoWSSTkm8-RDIhYrSsy6LYqJfivQgIqSuS3K4Hy4AhtKqAAFpIP-QDoFm+LwTgBEktY6KCMSDghIQWgLDoVhN2MBdQk4qB-1QTdUFYOoQPzI7uLgEC5oAuiVCuloaosMkIDmezoGk0x5O4wjshUehvLqWSQegELlJnPCCKWXb7Nq6AAfdEpYbBiGP2huSFPhsLN3zWCFL6-M6LsJ1eMJ0H1yyEk8LQKBqUpgbJugDBGPmuiAGo4oS1aktwrL1jU0jyPKnSbGAPSDKojrhprKc8ofLmZqFla1ogSKsrECBf2k4g8Il4ipc0mW5aqxXlam2tXoW-XxfISWNK0qjZfligUsM4zTIsqyvNs+TqMquW9O++qUEauhmo-NqjNcoPPJsl3Xfd6XtJtyPffazrQ45oCuYz54i3WIsQRQ0l0J3X8IeyVMPBYSDGDmEJQndMXoqzzT+LMTiUoANnPVNGBzQh3yhsvzfU8i+p46JQmpMw5jACey6LNl+xPTdkGyP8IEGGcBLQkgiQbswLBgFuQCQqAVBMEwEGvnC+A9XFTfN4BFwYSxLDeG3hfK+Fhl4P2MCHd+7psRfwfm7RAf9+RANEOWack5GZOmAHwdU9oZxM2ABgWEiZMFzgXEuCAPoJSPwsPmEAaxXbkAIgAPVYWw9hHDOFcK4VuSYABxRItovCkOAFRDCWFNISkZBfB0BCxH10btSIgG8+AOXcA4FgOEO6qIgI5ZeOEmSWgIgAAXltNAwkASTmLGrdEGtU4o2EnGkOAti7A7hUI4jG0BJJQGXrsLEEAn5QETLfDRIAZH4KwfIy+ijlGMB0XosIWj3QJN8UkxkhjyzWhCIfX8aB7wmDwRuAoZQa5oSxqYZuYS27SMYXU54ZSyRTgbgfKpngN4dzCN3MoESMGyKwaeHBiwikEIwDkv8+SAIjKwVQsQ+5H4FgYYwlh3DVlrI4bwgRQiIkblPFRIGJglEqLBLo9RjgDHSJEXsmJrS4mpNCecxk2iTmJJXhk6R-ZTFmHMfoSxwBrEuOhpxex2RHHHRsXUNxRIPEm0xj4vx9AAlBJCXfHZBDrktKbncl5aS3nPLUfo955YCLfX2jjG6cBwaCX4puNGv5fxQDcW+JK5M5LTOdLgfsRBGl0AGBAV4kF0x8t8AkEQRZrR7wRLdKlBQlT+lVEGZE4y8kiSmf0kkuollVmYS4EgQA)

**Comment by rkalis** [comment]
We got started on implementing the fixes discussed by @PHCitizen and @mr-zwets above, and integrating the required changes into this PR. We also started adding tests for this type inference to the github repo, based on the test cases from the TS playground link(s) above.

One difficulty we noticed is that it is impossible to import a JSON file `as const` in TypeScript, which would be required to have proper type inference when importing artifacts from JSON files. The workaround for this is to store the artifacts in a `.ts` files instead of JSON, but this does reduce their portability. See https://github.com/microsoft/TypeScript/issues/32063 for more info about this issue.

We'll continue the work on this on Thursday, and I think we should be able to finish most of the test cases and refactors by then. And then we'll just need to think if there are better ways to mitigate the "const json" issue.

**Comment by rkalis** [comment]
We finished the refactors + tests, so this should be good to go. The only drawback is still that we cannot infer proper types from JSON files, so we want to add an option to the `cashc` CLI to export a `.ts` file instead of a `.json` file, so that types can be inferred.

Next Tuesday we will add this option, update documentation and release this functionality. 🫡

**Review by rkalis — APPROVED** [review]

**Comment by rkalis** [comment]
Thanks @PHCitizen for this contribution. We added the `--format ts` flag that we talked about in the previous comment. Hopefully TypeScript makes it possible some time in the future to import JSON files `as const` so we don't need that workaround. But for now it is nice to give our users the option of proper typings if they use that flag.

**Pull request merged**
